source 'https://rubygems.org'
# gem 'github-pages', group: :jekyll_plugins
gem 'activesupport'
gem 'jekyll'
gem 'hash-joiner'
gem 'jekyll-seo-tag'
gem 'jekyll-include-cache'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'rouge'
gem 'jekyll-image-optim'
gem 'jekyll-image-size'
